### ISSUE TITLE
Wally-published version of Roact is out of date

### ISSUE THREAD

**Issue by Corecii** [Roblox/roact#374]
The most recent release of Roact is version `1.4.4`, but the most recent version on Wally is `1.4.2`. There have been a few requests to get Roact updated in the wally index since these releases include fixes to Luau typings.

Links:
* [Outdated `wally.toml`](https://github.com/Roblox/roact/blob/956891b70fdc5410e44e9664719cd0a9f7e6fabd/wally.toml)
* [Roact in the Wally index](https://github.com/UpliftGames/wally-index/blob/main/roblox/roact)

Additionally, it looks like `wally.toml` is out of sync with the index: the most recent version published to the index is `1.4.2`, but the version in `wally.toml` is older at `1.4.0`. Was the version bump for `wally.toml` not committed?

This can be resolved by:
1. Upping the version in `wally.toml` to `1.4.4`
2. Running `wally publish` using Wally after authenticating Wally with GitHub

**Comment by Corecii** [comment]
If publishing to Wally is not a habit, or if most engineers that publish releases do not have Wally on their computers, consider publishing using a GitHub action whenever you make a normal release!

<details><summary>Details</summary>

You may want to automatically up the `wally.toml` version to the release tag's version if updating `wally.toml` isn't a habit. 

To get wally, you can add it to `foreman.toml`:
```toml
wally = { source = "UpliftGames/wally", version = "0.3.1" }
```

To log in, you can generate an `auth.toml` on your local PC then store it in a GitHub secret, copying it to the right place:
```yaml
      - name: Log in to wally
        env:
          WALLY_AUTH: ${{ secrets.WALLY_AUTH }}
        run: |
          mkdir ~/.wally
          printenv WALLY_AUTH > ~/.wally/auth.toml
      - name: Push update to wally
        run: wally publish
```

</details>
